const messageData = [
  {
    index: 1,
    username: '郑宴',
    avatar: '../images/avatar-1.png',
    content: '手握999k纯金笔都不如最后落笔那一刻的爽快，是时候该轮到我们上场了！',
    img: '../images/pic-1.png',
    location: 'SAIC MOTOR Middle East FZE',
    time: '3分钟前',
    follows: ['金纪', '翁玉华', 'Lily', 'Rebecca', '简晰', '崔爽文', '葛文德', '张雅琴'],
    comments: [
      { user: '简晰', detail: '恭喜郑总！阿联酋最大的经销商都被你们拿下了！' },
      { user: '林晨', detail: '干得漂亮!' },
    ],
  },
  {
    index: 2,
    username: '穆青',
    avatar: '../images/avatar-2.png',
    content: '圣地亚哥车展，Let’shine! 今年的主题是第3代无人驾驶概念和全新的售后服务体系。总有人说不容易不容易，可我听见梦想在说 Why not?',
    img: '../images/pic-2.png',
    location: 'Santiago Chile Motor Show',
    time: '12分钟前',
    follows: ['Bob', '郑宴', '林晨', 'Andy', '王达文', 'Judy', 'Alice', '彭小华', '孙彦华'],
    comments: [
      { user: '林总', detail: '为梦想点赞👍👍👍' },
      { user: '王达文', detail: '规模一年比一年大了！' },
    ],
  },
  {
    index: 3,
    username: '贺平',
    avatar: '../images/avatar-3.png',
    content: 'Travel around Australia from south to north to get the first hand data. The annual',
    img: '../images/pic-3.png',
    location: 'Australia · Nelson Bay Rd · New South Wales',
    time: '3分钟前',
    follows: ['金纪', '翁玉华', 'Lily', 'Rebecca', '简晰', '崔爽文', '葛文德', '张雅琴',
      'Bob', '郑宴', '林晨', 'Andy', '王达文', 'Judy', 'Alice', '彭小华', '孙彦华'],
    comments: [
      { user: '路遥', replyTo: null, detail: '贺哥辛苦了，果然是全能市调王啊！' },
      { user: '贺平', replyTo: '路遥', detail: '谢谢，知己知彼才能百战百胜☺️' },
      {
        user: 'Toy', replyTo: '',
        detail: 'Compared with Chile, yours is just called ‘short haul’😜😜',
      },
    ],
  },
  {
    index: 6,
    username: '庄思捷',
    avatar: '../images/avatar-6.png',
    content: 'Today’s headline of NY times. Feel so proud to be a member of SAIC.',
    img: '../images/pic-6.png',
    location: '中国 · 上海',
    time: '2小时前',
    follows: ['金纪', '翁玉华', 'Lily', 'Rebecca', '简晰', '崔爽文', '葛文德', '张雅琴',
      'Bob', '郑宴', '林晨', 'Andy', '王达文', 'Judy', 'Alice', '彭小华', '孙彦华'],
  },
];
export default messageData;
